#include <bits/stdc++.h>
using namespace std;

string countandsay(int n ) {

	if (n == 1)
		return "1"; // base case
	if (n == 2)
		return "11"; // base case
	// string temp = "11" + '&';
	string str = "11"; // str ko inatialize kar diya
	int count = 1 ;
	for (int i = 3 ; i <= n ; i++) {
		string  temp = ""; // temp ko khaili kar diya // loop khatam hone ke bad dubaa yaha ayenge to string khali milega
		str = str + '&'; // ek extra char liya taki  n ko bhi include kar le
		// string  str = "";

		int l = str.size();
		for (int j = 1 ; j < l ; j++) {
			if (str[j] != str[j - 1]) { // agar match nahi hua to  uska cont aur wo char ko push kar do temp me
				temp = temp + to_string(count);//  count ek integer hain to_string usko string me kar dega
				temp = temp + str[j - 1];
				//temp = str ;
				count = 1 ; // yaha count ka value 1 kar diya
			}
			else
				count = count + 1; // agr match kkar raha hain to count badate jaoo
		}
		str = temp; // yaha updat kar diya string ko

	}
	return str ;
}

int  main() {
	// int t ;
	// cin>>t ;
	// while(t--){
	// 	int n ;   // this for gfg summission
	// 	cin>>n ;
	// 	cout<<countandsay(n)<<endl ;
	// }
	cout << countandsay(4);
	return 0 ;
}


// The first term is "1"

// Second term is "11", generated by reading first term as "One 1"
// (There is one 1 in previous term)

// Third term is "21", generated by reading second term as "Two 1"

// Fourth term is "1211", generated by reading third term as "One 2 One 1"

// and so on
// example
// Input: n = 3
// Output: 21

// Input: n = 5
// Output: 111221